### ISSUE TITLE
Tried to run it in Android Studio 1.0 and failed to build

### ISSUE THREAD

**Issue by skywalkerlw** [dannagle/PacketSender-Android#2]
when trying to import it into Android studio 1.0, there comes an error :

Error:(15, 0) Could not find property 'Compile' on project ':Packet Sender'.

and 

Error:The project is using an unsupported version of Gradle.

**Comment by dannagle** [comment]
This project was originally built with early Android Studio. I recommend using the code as a reference instead of a base.
